### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by JenspederM** [JenspederM/KaggleR#1]
### This is a todo list of functionality that I think would improve the package
- [ ] Add Kaggle Installer
- [ ] Extend function documentation
  - [ ] Function descriptions
  - [ ] Return values
  - [ ] Linkages between functions
- [ ] Add tests 
- [ ] Submit package to CRAN
- [x] Add verbose argument to utility functions
- [x] Wrap argument handling in helpers in accordance with DRY
- [x] Extend README
  - [x] Add Installation information (Perhaps ref to Kaggle API is enough)
  - [x] Add Authentication information (Perhaps ref to Kaggle API is enough)
